# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'
    csrf_protection: true
    http_method_override: true
    default_locale: en

    session:
        handler_id: null
        cookie_secure: true
        cookie_samesite: strict
    php_errors:
        log: false
