webpack_encore:
    output_path: '%kernel.project_dir%/public/build'
    # if using Encore.enableIntegrityHashes() and need the crossorigin attribute (default: false, or use 'anonymous' or 'use-credentials')
    # crossorigin: 'anonymous'
    preload: true
    strict_mode: true
    # cache: true
