version: '3.5'

services:
  web:
    image: webdevops/php-nginx-dev:8.2-alpine
    working_dir: /app
    volumes:
      - .:/app
      - ~/.ssh:/home/application/.ssh
      - ./vhost.conf:/opt/docker/nginx/conf.d/vhost.conf
    environment:
      - VIRTUAL_HOST=${VIRTUAL_HOST}
      - WEB_DOCUMENT_ROOT=/app/public

  node:
    image: node:14
    expose:
      - 8080
    volumes:
      - ./:/app
    working_dir: /app
    environment:
      - VIRTUAL_HOST=node.${VIRTUAL_HOST}
      - VIRTUAL_PORT=8080
    command: tail -f /dev/null

networks:
  default:
    external:
      name: proxy
