version: '3.5'

services:
  web:
    image: chrisb9/php8-nginx-xdebug:latest
    volumes:
      - .:/app
      - ~/.ssh:/home/application/.ssh
      - ~/.gitconfig_gitlab:/home/application/.gitconfig
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./vhost.conf:/opt/docker/nginx/conf.d/vhost.conf
    environment:
      - VIRTUAL_HOST=website.local.cben.dev
      - php.opcache.preload=/app/src/.preload

  node:
    image: node:latest
    expose:
      - 8080
    volumes:
      - ./:/app
    working_dir: /app
    environment:
      - VIRTUAL_HOST=node.website.local.cben.dev
      - VIRTUAL_PORT=8080
    command: tail -f /dev/null

networks:
  default:
    external:
      name: global
