version: '3.5'

services:
  web:
    image: chrisb9/php8:alpine-nginx
    volumes:
      - .:/app
      - ./vhost.prod.conf:/opt/docker/nginx/conf.d/vhost.conf
      - ./prod.ini:/usr/local/etc/php/conf.d/01-prod.ini
    environment:
      - VIRTUAL_HOST=cben.dev,cben.co,projects.cben.co
      - LETSENCRYPT_HOST=cben.co,cben.dev,projects.cben.co
      - LETSENCRYPT_EMAIL=chris@cben.co

networks:
  default:
    external:
      name: nginx-proxy
