name: CI
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: ssh deploy
      uses: easingthemes/ssh-deploy@v2.1.4
      with:
        SSH_PRIVATE_KEY: $SSH_PRIVATE_KEY
        # Remote host
        REMOTE_HOST: $SSH_HOST
        # Remote user
        REMOTE_USER: $SSH_USER
        # Remote port
        REMOTE_PORT: $SSH_PORT
        # Target directory
        TARGET: /var/www/
